"""initial_schema

Revision ID: cf88292e724f
Revises: 
Create Date: 2025-11-26 08:12:56.280133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf88292e724f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('media_store_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_created_by'), 'jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('media_store_sync_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('sync_attempted_at', sa.BigInteger(), nullable=True),
    sa.Column('sync_completed_at', sa.BigInteger(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_media_store_sync_status_next_retry_at'), 'media_store_sync_status', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_media_store_sync_status_sync_status'), 'media_store_sync_status', ['sync_status'], unique=False)
    op.create_table('queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enqueued_at', sa.BigInteger(), nullable=False),
    sa.Column('dequeued_at', sa.BigInteger(), nullable=True),
    sa.Column('worker_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_queue_dequeued_at', 'queue', ['dequeued_at'], unique=False)
    op.create_index('idx_queue_priority_enqueued', 'queue', ['priority', 'enqueued_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_queue_priority_enqueued', table_name='queue')
    op.drop_index('idx_queue_dequeued_at', table_name='queue')
    op.drop_table('queue')
    op.drop_index(op.f('ix_media_store_sync_status_sync_status'), table_name='media_store_sync_status')
    op.drop_index(op.f('ix_media_store_sync_status_next_retry_at'), table_name='media_store_sync_status')
    op.drop_table('media_store_sync_status')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_by'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
